# Generated by Django 4.1.5 on 2023-01-28 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9dcb93b0-ecfa-4981-bca0-14c9bf2c15e7'), primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad')),
                ('profit_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ganancia Por Unidad')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Compra C$')),
                ('buy_price_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Compra x Unidad C$')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Venta C$')),
                ('sell_price_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de Venta x Unidad C$')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Total')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
