# Generated by Django 4.1.5 on 2023-01-28 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='sell_price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52598854-b9f2-497f-b882-9db259cf3d3b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='profit_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ganancia Por Unidad C$'),
        ),
    ]
