# Generated by Django 4.1.5 on 2023-01-28 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_remove_inventory_sell_price_alter_inventory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad Actual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6245c847-8bfb-44e8-a9da-288392df32fe'), primary_key=True, serialize=False),
        ),
    ]
