# Generated by Django 4.1.5 on 2023-01-29 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_inventory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['product', 'product__brand__name', 'product__color'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
    ]
