# Generated by Django 4.1.5 on 2023-01-28 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fe6ca85-3530-4a08-b744-4fdbbff6edfe'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35e0f535-7653-45e3-8ecd-fba1f90c90ba'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5a49135-d892-4745-bd71-16094a204f68'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitmeasurement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19b44d1f-6afc-4a8c-82cc-f82058c797df'), primary_key=True, serialize=False),
        ),
    ]
