# Generated by Django 4.1.5 on 2023-01-28 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3679a302-31eb-47b3-8911-3446179ce8d1'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47eccc9f-49bd-41ad-95b4-97d6c870013b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2120232b-9ca7-4358-8dd4-3920f5e53e8a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitmeasurement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('39a759c0-0406-45de-b76f-79d8a97a70df'), primary_key=True, serialize=False),
        ),
    ]
